<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="23" started-at="2017-03-04T18:26:02Z" finished-at="2017-03-04T18:26:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="23" started-at="2017-03-04T18:26:02Z" finished-at="2017-03-04T18:26:02Z">
      <class name="lib.com.DataSheet">
        <test-method status="FAIL" signature="test1()[pri:0, instance:lib.com.DataSheet@36fc695d]" name="test1" duration-ms="8" started-at="2017-03-04T23:56:02Z" finished-at="2017-03-04T23:56:02Z">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problems: 
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type AWTException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problems: 
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type AWTException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException

	at lib.com.DataSheet.test1(DataSheet.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- lib.com.DataSheet -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
